DECLARE 
CURSOR FECHAS_PROCESO IS
    SELECT TO_DATE('07/06/2019','DD/MM/YYYY') + ROWNUM -1 Fecha
    FROM ALL_OBJECTS
    WHERE ROWNUM <=TO_DATE('17/06/2019','DD/MM/YYYY') -TO_DATE('07/06/2019','DD/MM/YYYY')+1;
BEGIN 
     FOR I IN FECHAS_PROCESO LOOP 
        IF I.FECHA IN (TO_DATE('07/06/2019'), TO_DATE('13/06/2019'),TO_DATE('17/06/2019')) THEN  
            FITBANK.MAYORIZACION(I.FECHA);
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Ejecutado: '||I.FECHA);
        END IF;              
     END LOOP;
END;