/*------------------- 18-7051 CONSULTA DE CATALOGO DE TRANSACCIONES SUBTIPO----------------------------------*/

INSERT INTO TSUBSISTEMATRANSACCIONESID (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, ORDENMENU, PRESENTARENMENU, INTERNA, FORMULARIOBASE, AFECTAINMOVILIZACION, CGRUPOTRANSACCION, PRESENTARENREVERSO, CNIVELMENU, LISTAVALOR, USACACHE, SUMACOMPONENTES, PROVISION, COMPLETARRUBROS, LOTEGENERICO, VERIFICANIVELSEGURIDAD, CUSUARIO_INGRESO, FINGRESO, ACUMULACONTADOR, PAGINA, ORIGENDESTINO, CONTROLAEFECTIVO, REQUIEREAUTORIZACION, EJECUTAENAUTORIZACION, REPORTEENFACTURACION) VALUES ('18', '7051', '01', 0, '0', '1', '1', '0', null, null, null, null, '0', null, '0', '0', null, '0', null, null, '0', null, null, '0', '0', '0', '0');

INSERT INTO TSUBSISTEMATRANSACCIONES (CIDIOMA, CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, FHASTA, FDESDE, DESCRIPCION, SIGLAS, VERSIONCONTROL) VALUES ('ES', '18', '7051', '01', TO_TIMESTAMP('2999-12-31', 'YYYY-MM-DD'), SYSDATE, 'CONSULTA DE CATALOGO DE TRANSACCIONES SUBTIPO', null, 0);
INSERT INTO TCOMPANIATRANSACCIONES (CPERSONA_COMPANIA, CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, VERSIONCONTROL) VALUES (2, '18', '7051', '01', 0);

/*------------------- 18-7061 TRANSACCION REGISTRO DE TRANSACCIONES DE CANALES----------------------------------*/

INSERT INTO TSUBSISTEMATRANSACCIONESID (CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, ORDENMENU, PRESENTARENMENU, INTERNA, FORMULARIOBASE, AFECTAINMOVILIZACION, CGRUPOTRANSACCION, PRESENTARENREVERSO, CNIVELMENU, LISTAVALOR, USACACHE, SUMACOMPONENTES, PROVISION, COMPLETARRUBROS, LOTEGENERICO, VERIFICANIVELSEGURIDAD, CUSUARIO_INGRESO, FINGRESO, ACUMULACONTADOR, PAGINA, ORIGENDESTINO, CONTROLAEFECTIVO, REQUIEREAUTORIZACION, EJECUTAENAUTORIZACION, REPORTEENFACTURACION) VALUES ('18', '7061', '01', 0, '0', '1', '1', '0', null, null, null, null, '0', null, '0', '0', null, '0', null, null, '0', null, null, '0', '0', '0', '0');

INSERT INTO TSUBSISTEMATRANSACCIONES (CIDIOMA, CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, FHASTA, FDESDE, DESCRIPCION, SIGLAS, VERSIONCONTROL) VALUES ('ES', '18', '7061', '01', TO_TIMESTAMP('2999-12-31', 'YYYY-MM-DD'), SYSDATE, 'REGISTRO DE TRANSACCIONES DE CANALES', null, 0);
INSERT INTO TCOMPANIATRANSACCIONES (CPERSONA_COMPANIA, CSUBSISTEMA, CTRANSACCION, VERSIONTRANSACCION, VERSIONCONTROL) VALUES (2, '18', '7061', '01', 0);


