/*<TOAD_FILE_CHUNK>*/
DROP TABLE TTRANSACCIONESSUBTIPOID CASCADE CONSTRAINTS ;

CREATE TABLE TTRANSACCIONESSUBTIPOID
(
    CTRANSSUBTIPO        VARCHAR2(10) NOT NULL
    CONSTRAINT IPKTRANSSUBTIPOID
    PRIMARY KEY
)
//*<TOAD_FILE_CHUNK>*/
DROP TABLE TTRANSACCIONESSUBTIPO CASCADE CONSTRAINTS ;

-- CATALOGO DE TRANSACCIONES SUBTIPO
CREATE TABLE TTRANSACCIONESSUBTIPO
(
  CIDIOMA        	VARCHAR2(3)  NOT NULL
    CONSTRAINT FKIDITRANSSUBTIPO
    REFERENCES TIDIOMASID,
  CTRANSSUBTIPO         VARCHAR2(10)  NOT NULL
    CONSTRAINT FKTRANSSUBTIPOID
    REFERENCES TTRANSACCIONESSUBTIPOID,
  SUBTIPO 		VARCHAR2(50) NOT NULL,
  FHASTA         	TIMESTAMP(6) NOT NULL,
  FDESDE         	TIMESTAMP(6) NOT NULL,
  DESCRIPCION    	VARCHAR2(50) NOT NULL,
  VERSIONCONTROL 	NUMBER(22) DEFAULT 0,
  CONSTRAINT 		IPKTRANSSUBTIPO
  PRIMARY KEY (CIDIOMA, CTRANSSUBTIPO, FHASTA)
)
//*<TOAD_FILE_CHUNK>*/

CREATE INDEX IFKTRANSSUBTIPOID
  ON TTRANSACCIONESSUBTIPO (CTRANSSUBTIPO)
/

