--EL NUMERO TOTAL DEBE SER IGAL AL TOTAL REASIGNADO
SELECT COUNT(*)
FROM TCUENTA
WHERE CSUBSISTEMA='05'
AND FHASTA=FNCFHASTA
AND TRUNC(FDESDE)=TRUNC(SYSDATE)
AND CUSUARIO_MODIFICACION =:pUsuarioModifica
AND CUSUARIO_OFICIALCUENTA=:pvOficialNuevo
and coficina=:pvOficina;

--BORRO LOS REGISTROS
DELETE  TCUENTA
WHERE CSUBSISTEMA='05'
AND FHASTA=FNCFHASTA
AND TRUNC(FDESDE)=TRUNC(SYSDATE)
AND CUSUARIO_MODIFICACION =:pUsuarioModifica
AND CUSUARIO_OFICIALCUENTA=:pvOficialNuevo
and coficina=:pvOficina;

--CUENTA PARA ACTIVAR
SELECT COUNT(*)
FROM TCUENTA TC
WHERE CSUBSISTEMA='05'
AND CUSUARIO_OFICIALCUENTA=:pvOficialAnterior
and coficina=:pvOficina
AND TRUNC(FHASTA)=TRUNC(SYSDATE);

--CUENTA PARA ACTIVAR
UPDATE TCUENTA SET FHASTA=FNCFHASTA
WHERE CSUBSISTEMA='05'
AND CUSUARIO_OFICIALCUENTA=:pvOficialAnterior
and coficina=:pvOficina
AND TRUNC(FHASTA)=TRUNC(SYSDATE);

--REVISA
SELECT *
FROM TCUENTA TC
WHERE CSUBSISTEMA='05'
AND FHASTA=FNCFHASTA
AND TRUNC(FDESDE)=TRUNC(SYSDATE)
AND CUSUARIO_MODIFICACION='1787'
AND CESTATUSCUENTA='002';

