Insert into FITBANK.tcomandosmantenimiento 
(CSUBSISTEMA,CTRANSACCION,VERSIONTRANSACCION,SCOMANDO,EVENTO,COMANDO,ORDEN,USACACHE,
TIPOCOMANDO,ACTIVADO,CANALESEXCLUIDOS,PARAMETRO,VERSIONCONTROL,EJECUTADOPOR,CLASSLOADER)
values ('24','4051','01','1','I','com.fitbank.accounting.query.AutomaticAccountantVoucher',
'1','0','CON','1',null,null,'0','F',null);
