/* Formatted on 29/08/2019 9:03:17 (QP5 v5.287) */
CREATE TABLE FITBANK.TSPI4DETALLES
(
   FECHAPROCESO                   DATE NOT NULL,
   NUMEROCORTE                    INT NOT NULL,
   FECHAVALIDACIONBCE             TIMESTAMP,
   SGIROTRANSFERENCIAAUTORIZADO   NUMBER NOT NULL,
   SECUENCIALUNICOBCE             INT NOT NULL,
   FECHACOMPENSACIONCE            TIMESTAMP,
   ESTATUSOPI                     INT NOT NULL,
   DETALLE                        VARCHAR (500) NOT NULL
);

CREATE INDEX FITBANK.IN_TSPI4
   ON FITBANK.TSPI4DETALLES (SGIROTRANSFERENCIAAUTORIZADO,
                             FECHAPROCESO,
                             ESTATUSOPI)
   LOGGING
   TABLESPACE TBS_FITBANKINDEX
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (MAXSIZE UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT);

CREATE INDEX FITBANK.IN_TGIROSTRANSF_NUMDOC
   ON FITBANK.tgirostransferenciasautorizado (NUMERODOCUMENTO)
   LOGGING
   TABLESPACE TBS_FITBANKINDEX
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (MAXSIZE UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT);