/* ACTUALIZACIÓN
 Fecha : 27/09/2019 
 Desarrollo: Christian Casa - Gestión de Aplicaciones
 Módulo Ventas Fitbank - NOTA DE CRÉDITO
 Usuario: José Luis Soria  - Contabilidad
 Descripción: para procesar las notas de crédito del módulo de Ventas es necesario incrementar 2 campos 
 (CTARIFAIVA y PORCENTAJETARIFAIVA) en la tabla TCNOTACREDITODEBITO 
 */
 
 -- ACTUALIZACIÓN --
ALTER TABLE FITBANK.TCNOTACREDITODEBITO ADD CTARIFAIVA VARCHAR2(1);
ALTER TABLE FITBANK.TCNOTACREDITODEBITO ADD PORCENTAJETARIFAIVA NUMBER(6,2);

-- ROLLBACK --
ALTER TABLE FITBANK.TCNOTACREDITODEBITO DROP COLUMN CTARIFAIVA;
ALTER TABLE FITBANK.TCNOTACREDITODEBITO DROP COLUMN CTARIFAIVA;
